Add images to features
AY2122S2-CS2103T-T12-1/tp pull request #106
Opened 2022-03-26 03:35 UTC by e0544333

2022-03-26 08:49 UTC, Fenway17 commented on docs/UserGuide.md
> +Q: What if I key in the wrong command?
Need to add a double space (aka. line break) to force the answer to be in the next line

2022-03-26 08:50 UTC, Fenway17 requested changes
Need to add double spaces (aka. line break) in the FAQ section

2022-03-26 11:43 UTC, lzf834 reviewed
Looks good! Thanks for adding the images. I think just need to correct the changes as mentioned by Yong Rui before merging in.

2022-03-27 02:31 UTC, lzf834 commented
Not sure what the issue was yesterday, but after re-running the workflow, the error has disappeared.
Will merge the changes now.

2022-03-27 05:24 UTC, Fenway17 approved these changes
Looks good!

2022-03-27 05:24 UTC, merged