Test Case and UG updates
AY2122S2-CS2103T-T12-1/tp pull request #181
Opened 2022-04-06 11:26 UTC by lzf834

UG update:
- right-click help menu
 - undo/redo function explanation
 - cut/copy/paste
 - delete
 - select all
- Add tests for attributes in ParserUtilTest:
 - Phone
 - ClassCode
 - Name
 - Status

2022-04-06 17:05 UTC, Fenway17 requested changes
minor checkstyle related errors in UG

2022-04-06 17:05 UTC, Fenway17 commented on docs/UserGuide.md
> +##Right-Click Help Menu
needs to have a space here

2022-04-07 03:22 UTC, lzf834 commented on docs/UserGuide.md
> +##Right-Click Help Menu
alright fixed it in the latest commit

2022-04-07 05:33 UTC, Fenway17 approved these changes

2022-04-07 05:33 UTC, merged